### ISSUE TITLE
Getting an error message.

### ISSUE THREAD

**Issue by DurbanLegacy** [rupeshmohanty/chat-api#2]
[Thu Jan 14 19:13:29 2021] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /home/runner/chatapp/scripts/db.php:3
Stack trace:
#0 /home/runner/chatapp/index.php(7): include()
#1 {main}
  thrown in /home/runner/chatapp/scripts/db.php on line 3
[Thu Jan 14 19:13:29 2021] 172.18.0.1:56956 [500]: / - Uncaught Error: Call to undefined function mysqli_connect() in /home/runner/chatapp/scripts/db.php:3
Stack trace:
#0 /home/runner/chatapp/index.php(7): include()
#1 {main}
  thrown in /home/runner/chatapp/scripts/db.php on line 3
  
  This is the error message i get when running the code. It is all put under the correct files

**Comment by rupeshmohanty** [comment]
You need to create a db.php file where you can give the details of the database and the server you are using.

The syntax is :
$conn = mysqli_connect("<server_ip>","<admin_username>","<admin_password>","<database_name>") or die(mysqli_error($conn));

**Comment by DurbanLegacy** [comment]
### _**ok idk how**_

**Comment by rupeshmohanty** [comment]
First you have to install the Xampp control panel for this code to work
--> Install Xampp
--> After installation a xampp folder will be created in the directory you mentioned while installation.
--> In the xampp/htdocs folder clone this repo.
--> Then run the xampp control panel and click start for apache and mysql
--> The go to localhost/phpmyadmin/ in your browser and there you can setup the database and the tables for this project.
--> After setting it up try running this project in by using this url "localhost/<project_name>"
